

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'
    - 'bin/*'
    - 'app/controllers/my_devise/registrations_controller.rb'

Metrics/BlockLength:
  Exclude:
  - 'config/environments/development.rb'
  - 'db/schema.rb'

Metrics/LineLength:
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'bin/*'
    - 'Rakefile'
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude: 
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
  
Style/Documentation:
  Exclude:
  
Metrics/AbcSize:
  Exclude:

Lint/Void:
  Exclude:

Metrics/ClassLength:
  Exclude:

Metrics/MethodLength:
  Exclude:
  - 'db/migrate/20191104075954_devise_create_users.rb'
  
Style/Documentation:
  Exclude:
  
Metrics/AbcSize:
  Exclude:

Lint/Void:
  Exclude:
  - 'app/controllers/omniauth_callbacks_controller.rb'

Style/MixinUsage:
  Exclude:
  - 'bin/*'